// frontend/src/pages/goal-templates/EditGoalTemplate.tsx
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Input } from '../../components/ui/input'
import { Label } from '../../components/ui/label'
import { Textarea } from '../../components/ui/textarea'
import { Button } from '../../components/ui/button'
import { Badge } from '../../components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../../components/ui/select'
import { apiFetch } from '../../utils/api'
import { toast } from 'sonner'
import { useAuth } from '../../contexts/AuthContext'
import { ArrowLeft, Home } from 'lucide-react'

interface CategoryDto { id: number; name: string }

interface GoalTemplateDto {
  temp_id: number
  temp_title: string
  temp_description: string
  temp_performance_factor: string
  temp_importance: string
  temp_weightage: number
  categories: CategoryDto[]
}

const EditGoalTemplate = () => {
  const navigate = useNavigate()
  const params = useParams()
  const templateId = params.id ? Number(params.id) : undefined
  const { user } = useAuth()

  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)

  const [tempTitle, setTempTitle] = useState('')
  const [tempDescription, setTempDescription] = useState('')
  const [tempPerformanceFactor, setTempPerformanceFactor] = useState('')
  const [tempImportance, setTempImportance] = useState('')
  const [tempWeightage, setTempWeightage] = useState<number | ''>('')
  const [categories, setCategories] = useState<string[]>([])

  const [allCategories, setAllCategories] = useState<CategoryDto[]>([])
  const [newCategory, setNewCategory] = useState('')

  const isEdit = useMemo(() => typeof templateId === 'number' && !Number.isNaN(templateId), [templateId])

  const isManagerOrAbove = (roles?: string, level?: number | null) => {
    if (roles && /manager|lead|head|director|vp|chief|cxo|cto|ceo|admin/i.test(roles)) return true
    if (typeof level === 'number') return level > 2
    return false
  }

  useEffect(() => {
    // Access guard
    if (!isManagerOrAbove(user?.emp_roles, user?.emp_roles_level)) {
      toast.error('You are not authorized to manage goal templates')
      navigate('/goal-templates')
      return
    }

    const init = async () => {
      try {
        setLoading(true)
        // Load available categories (optional)
        const catRes = await apiFetch<CategoryDto[]>('/api/goals/categories')
        if (catRes.ok && catRes.data) setAllCategories(catRes.data)

        if (isEdit && templateId) {
          const res = await apiFetch<GoalTemplateDto>(`/api/goals/templates/${templateId}`)
          if (!res.ok || !res.data) throw new Error(res.error || 'Failed to load template')
          const t = res.data
          setTempTitle(t.temp_title)
          setTempDescription(t.temp_description)
          setTempPerformanceFactor(t.temp_performance_factor)
          setTempImportance(t.temp_importance)
          setTempWeightage(t.temp_weightage)
          setCategories(Array.isArray(t.categories) ? t.categories.map(c => c.name) : [])
        }
      } catch (e: any) {
        toast.error(e?.message || 'Failed to load data')
      } finally {
        setLoading(false)
      }
    }
    void init()
  }, [isEdit, templateId, user])

  const addCategory = () => {
    const name = newCategory.trim()
    if (!name) return
    if (categories.includes(name)) {
      setNewCategory('')
      return
    }
    setCategories(prev => [...prev, name])
    setNewCategory('')
  }

  const removeCategory = (name: string) => {
    setCategories(prev => prev.filter(c => c !== name))
  }

  const save = async () => {
    if (!tempTitle.trim()) {
      toast.error('Title is required')
      return
    }
    const weight = typeof tempWeightage === 'number' ? tempWeightage : parseInt(String(tempWeightage || '0'))
    if (!weight || weight < 1 || weight > 100) {
      toast.error('Weightage must be between 1 and 100')
      return
    }

    const payload = {
      temp_title: tempTitle.trim(),
      temp_description: tempDescription.trim(),
      temp_performance_factor: tempPerformanceFactor.trim(),
      temp_importance: tempImportance.trim(),
      temp_weightage: weight,
      categories: categories, // array of names per backend contract
    }

    try {
      setSaving(true)
      if (isEdit && templateId) {
        const res = await apiFetch(`/api/goals/templates/${templateId}`, {
          method: 'PUT',
          body: JSON.stringify(payload),
        })
        if (!res.ok) throw new Error(res.error || 'Failed to update goal template')
        toast.success('Template updated')
      } else {
        const res = await apiFetch(`/api/goals/templates`, {
          method: 'POST',
          body: JSON.stringify(payload),
        })
        if (!res.ok) throw new Error(res.error || 'Failed to create goal template')
        toast.success('Template created')
      }
      navigate('/goal-templates')
    } catch (e: any) {
      toast.error(e?.message || 'Save failed')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="mx-auto max-w-4xl p-4 sm:p-6">
      <div className="flex items-center justify-between gap-3 mb-6">
        <div className="flex items-center gap-3 sm:gap-4">
          <Button
            variant="outline"
            size="sm"
            onClick={() => navigate('/goal-templates')}
            className="flex items-center gap-2"
            aria-label="Back"
            title="Back"
          >
            <ArrowLeft className="h-4 w-4" />
            <span className="hidden sm:inline sm:ml-2">Back</span>
          </Button>
          <h1 className="text-2xl font-bold">{isEdit ? 'Edit Goal Template' : 'Create Template'}</h1>
        </div>
        <div className="flex items-center">
          <Button
            size="sm"
            onClick={() => navigate('/')}
            className="hidden sm:inline-flex items-center gap-2 bg-primary hover:bg-primary/90 text-primary-foreground"
            aria-label="Home"
            title="Home"
          >
            <Home className="h-4 w-4" />
            <span className="hidden sm:inline sm:ml-2">Home</span>
          </Button>
        </div>
      </div>

      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="text-lg">
            {isEdit ? 'Update Template Details' : 'Template Information'}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div>
            <Label htmlFor="title">Title</Label>
            <Input
              id="title"
              value={tempTitle}
              onChange={(e) => setTempTitle(e.target.value)}
              disabled={loading || saving}
              className="transition-shadow focus:shadow-sm motion-reduce:transition-none"
              aria-describedby="title-help"
            />
            <p id="title-help" className="mt-1 text-xs text-muted-foreground">Give your template a concise, descriptive title.</p>
          </div>
          <div>
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              value={tempDescription}
              onChange={(e) => setTempDescription(e.target.value)}
              disabled={loading || saving}
              className="transition-shadow focus:shadow-sm motion-reduce:transition-none"
              aria-describedby="description-help"
            />
            <p id="description-help" className="mt-1 text-xs text-muted-foreground">Optional: add context so appraisers understand the goal’s intent.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="perf">Performance Factor</Label>
              <Input
                id="perf"
                value={tempPerformanceFactor}
                onChange={(e) => setTempPerformanceFactor(e.target.value)}
                disabled={loading || saving}
                className="transition-shadow focus:shadow-sm motion-reduce:transition-none"
                aria-describedby="perf-help"
              />
              <p id="perf-help" className="mt-1 text-xs text-muted-foreground">E.g., Quality, Delivery, Ownership, Collaboration.</p>
            </div>
            <div>
              <Label htmlFor="importance">Importance</Label>
              <Select value={tempImportance} onValueChange={setTempImportance} disabled={loading || saving}>
                <SelectTrigger>
                  <SelectValue placeholder="Select importance level" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="High">🔴 High Priority</SelectItem>
                  <SelectItem value="Medium">🟡 Medium Priority</SelectItem>
                  <SelectItem value="Low">🟢 Low Priority</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="weight">Weightage (%)</Label>
              <Input
                id="weight"
                type="number"
                min={1}
                max={100}
                value={tempWeightage}
                onChange={(e) => setTempWeightage(e.target.value === '' ? '' : parseInt(e.target.value))}
                disabled={loading || saving}
                className="transition-shadow focus:shadow-sm motion-reduce:transition-none"
                aria-describedby="weight-help"
              />
              <p id="weight-help" className="mt-1 text-xs text-muted-foreground">Must be between 1–100. Appraisal total must sum to 100%.</p>
            </div>
          </div>

          <div className="grid gap-2">
            <Label>Categories</Label>
            <div className="flex flex-col sm:flex-row gap-2">
              <Input
                placeholder="Add category name"
                value={newCategory}
                onChange={(e) => setNewCategory(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); addCategory() } }}
                autoComplete="off"
                disabled={loading || saving}
                className="w-full sm:flex-1 transition-shadow focus:shadow-sm motion-reduce:transition-none"
                aria-describedby="category-help"
              />
              <Button type="button" onClick={addCategory} disabled={loading || saving}>Add</Button>
            </div>
            <p id="category-help" className="text-xs text-muted-foreground">Press Enter to add. Avoid duplicates.</p>
            {allCategories.length > 0 && (
              <div className="flex flex-wrap gap-2 text-xs text-muted-foreground">
                <span>Suggestions:</span>
                {allCategories.map(c => (
                  <button
                    key={c.id}
                    type="button"
                    className="px-2 py-1 rounded border hover:bg-muted"
                    onClick={() => setNewCategory(c.name)}
                    disabled={loading || saving}
                  >
                    {c.name}
                  </button>
                ))}
              </div>
            )}
            <div className="flex flex-wrap gap-2 mt-2">
              {categories.map((c) => (
                <Badge key={c} variant="outline" className="flex items-center gap-2">
                  {c}
                  <button
                    type="button"
                    className="text-xs text-muted-foreground hover:text-foreground"
                    onClick={() => removeCategory(c)}
                    disabled={loading || saving}
                    aria-label={`Remove category ${c}`}
                  >
                    ×
                  </button>
                </Badge>
              ))}
            </div>
          </div>

          <div className="flex flex-col-reverse sm:flex-row items-stretch sm:items-center justify-end gap-2 sm:gap-3 pt-4 border-t">
            <Button variant="outline" type="button" onClick={() => navigate('/goal-templates')} disabled={saving} className="w-full sm:w-auto">
              Cancel
            </Button>
            <Button type="button" onClick={save} disabled={saving || loading} className="w-full sm:w-auto px-6">
              {saving ? 'Saving...' : (isEdit ? 'Save Changes' : 'Create Template')}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Mobile-only floating Home button for better discoverability */}
      <Button
        onClick={() => navigate('/')}
        title="Home"
        aria-label="Home"
        className="sm:hidden fixed bottom-20 right-4 z-50 rounded-full h-12 w-12 p-0 bg-primary text-primary-foreground shadow-lg hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary/30"
      >
        <Home className="h-5 w-5" />
      </Button>
    </div>
  )
}

export default EditGoalTemplate

// frontend-angular/src/app/features/goal-templates/edit-goal-template/edit-goal-template.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule, FormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatChipsModule } from '@angular/material/chips';
import { MatSnackBar } from '@angular/material/snack-bar';
import { AppraisalService, GoalTemplate, GoalCategory } from '../../../core/services/appraisal.service';
import { AuthService } from '../../../core/services/auth.service';

interface ExtendedGoalTemplate extends GoalTemplate {
  categories?: GoalCategory[];
}

@Component({
  selector: 'app-edit-goal-template',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    MatSelectModule,
    MatChipsModule
  ],
  template: `
    <div class="mx-auto max-w-4xl p-4 sm:p-6">
      <!-- Header -->
      <div class="flex items-center justify-between gap-3 mb-6">
        <div class="flex items-center gap-3 sm:gap-4">
          <button
            mat-stroked-button
            (click)="goBack()"
            class="flex items-center gap-2"
            aria-label="Back"
            title="Back"
          >
            <mat-icon>arrow_back</mat-icon>
            <span class="hidden sm:inline">Back</span>
          </button>
          <h1 class="text-2xl font-bold">{{ isEdit() ? 'Edit Goal Template' : 'Create Template' }}</h1>
        </div>
        <div class="flex items-center">
          <button
            mat-stroked-button
            (click)="goHome()"
            class="hidden sm:inline-flex items-center gap-2"
            aria-label="Home"
            title="Home"
          >
            <mat-icon>home</mat-icon>
            <span class="hidden sm:inline">Home</span>
          </button>
        </div>
      </div>

      <!-- Form Card -->
      <mat-card class="shadow-lg">
        <mat-card-header>
          <mat-card-title class="text-lg">
            {{ isEdit() ? 'Update Template Details' : 'Template Information' }}
          </mat-card-title>
        </mat-card-header>
        <mat-card-content class="space-y-6">
          <form [formGroup]="templateForm" (ngSubmit)="save()" class="space-y-6">
            <!-- Title -->
            <mat-form-field appearance="outline" class="w-full">
              <mat-label>Title</mat-label>
              <input
                matInput
                formControlName="title"
                [disabled]="loading() || saving()"
                placeholder="Enter template title"
              >
              <mat-hint>Give your template a concise, descriptive title.</mat-hint>
              @if (templateForm.get('title')?.hasError('required') && templateForm.get('title')?.touched) {
                <mat-error>Title is required</mat-error>
              }
            </mat-form-field>

            <!-- Description -->
            <mat-form-field appearance="outline" class="w-full">
              <mat-label>Description</mat-label>
              <textarea
                matInput
                formControlName="description"
                [disabled]="loading() || saving()"
                rows="3"
                placeholder="Enter template description"
              ></textarea>
              <mat-hint>Optional: add context so appraisers understand the goal's intent.</mat-hint>
            </mat-form-field>

            <!-- Performance Factor and Importance -->
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <mat-form-field appearance="outline">
                <mat-label>Performance Factor</mat-label>
                <input
                  matInput
                  formControlName="performanceFactor"
                  [disabled]="loading() || saving()"
                  placeholder="e.g., Quality, Delivery, Ownership"
                >
                <mat-hint>E.g., Quality, Delivery, Ownership, Collaboration.</mat-hint>
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Importance</mat-label>
                <mat-select formControlName="importance" [disabled]="loading() || saving()">
                  <mat-option value="High">🔴 High Priority</mat-option>
                  <mat-option value="Medium">🟡 Medium Priority</mat-option>
                  <mat-option value="Low">🟢 Low Priority</mat-option>
                </mat-select>
              </mat-form-field>
            </div>

            <!-- Weightage -->
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <mat-form-field appearance="outline">
                <mat-label>Weightage (%)</mat-label>
                <input
                  matInput
                  type="number"
                  min="1"
                  max="100"
                  formControlName="weightage"
                  [disabled]="loading() || saving()"
                  placeholder="Enter weightage percentage"
                >
                <mat-hint>Must be between 1–100. Appraisal total must sum to 100%.</mat-hint>
                @if (templateForm.get('weightage')?.hasError('required') && templateForm.get('weightage')?.touched) {
                  <mat-error>Weightage is required</mat-error>
                }
                @if (templateForm.get('weightage')?.hasError('min') || templateForm.get('weightage')?.hasError('max')) {
                  <mat-error>Weightage must be between 1 and 100</mat-error>
                }
              </mat-form-field>
            </div>

            <!-- Categories -->
            <div class="space-y-2">
              <label class="text-sm font-medium">Categories</label>
              <div class="flex flex-col sm:flex-row gap-2">
                <mat-form-field appearance="outline" class="flex-1">
                  <mat-label>Add category name</mat-label>
                  <input
                    matInput
                    [(ngModel)]="newCategory"
                    [ngModelOptions]="{standalone: true}"
                    (keydown.enter)="addCategory()"
                    [disabled]="loading() || saving()"
                    placeholder="Enter category name"
                  >
                </mat-form-field>
                <button
                  mat-raised-button
                  type="button"
                  (click)="addCategory()"
                  [disabled]="loading() || saving() || !newCategory.trim()"
                >
                  Add
                </button>
              </div>
              <p class="text-xs text-gray-600">Press Enter to add. Avoid duplicates.</p>

              <!-- Category suggestions -->
              @if (allCategories().length > 0) {
                <div class="flex flex-wrap gap-2 text-xs text-gray-600">
                  <span>Suggestions:</span>
                  @for (category of allCategories(); track category.id) {
                    <button
                      type="button"
                      class="px-2 py-1 rounded border hover:bg-gray-100"
                      (click)="newCategory = category.name"
                      [disabled]="loading() || saving()"
                    >
                      {{ category.name }}
                    </button>
                  }
                </div>
              }

              <!-- Selected categories -->
              <mat-chip-set class="mt-2">
                @for (category of selectedCategories(); track category) {
                  <mat-chip (removed)="removeCategory(category)" class="bg-rose-50 text-rose-700">
                    {{ category }}
                    <mat-icon matChipRemove>cancel</mat-icon>
                  </mat-chip>
                }
              </mat-chip-set>
            </div>

            <!-- Action buttons -->
            <div class="flex flex-col-reverse sm:flex-row items-stretch sm:items-center justify-end gap-2 sm:gap-3 pt-4 border-t">
              <button
                mat-stroked-button
                type="button"
                (click)="goBack()"
                [disabled]="saving()"
                class="w-full sm:w-auto"
              >
                Cancel
              </button>
              <button
                mat-raised-button
                color="primary"
                type="submit"
                [disabled]="saving() || loading() || templateForm.invalid"
                class="w-full sm:w-auto px-6"
              >
                {{ saving() ? 'Saving...' : (isEdit() ? 'Save Changes' : 'Create Template') }}
              </button>
            </div>
          </form>
        </mat-card-content>
      </mat-card>

      <!-- Mobile-only floating Home button -->
      <button
        mat-fab
        (click)="goHome()"
        title="Home"
        aria-label="Home"
        class="sm:hidden fixed bottom-20 right-4 z-50"
      >
        <mat-icon>home</mat-icon>
      </button>
    </div>
  `,
  styles: [`
    .space-y-6 > * + * {
      margin-top: 1.5rem;
    }
    
    .space-y-2 > * + * {
      margin-top: 0.5rem;
    }
  `]
})
export class EditGoalTemplateComponent implements OnInit {
  private router = inject(Router);
  private route = inject(ActivatedRoute);
  private fb = inject(FormBuilder);
  private appraisalService = inject(AppraisalService);
  private authService = inject(AuthService);
  private snackBar = inject(MatSnackBar);

  loading = signal(false);
  saving = signal(false);
  isEdit = signal(false);
  allCategories = signal<GoalCategory[]>([]);
  selectedCategories = signal<string[]>([]);
  newCategory = '';

  templateForm: FormGroup = this.fb.group({
    title: ['', Validators.required],
    description: [''],
    performanceFactor: [''],
    importance: [''],
    weightage: ['', [Validators.required, Validators.min(1), Validators.max(100)]]
  });

  private templateId?: number;

  ngOnInit() {
    // Check authorization
    if (!this.isManagerOrAbove()) {
      this.snackBar.open('You are not authorized to manage goal templates', 'Close', { duration: 3000 });
      this.router.navigate(['/goal-templates']);
      return;
    }

    // Get template ID from route
    const id = this.route.snapshot.paramMap.get('id');
    if (id && !isNaN(Number(id))) {
      this.templateId = Number(id);
      this.isEdit.set(true);
    }

    this.loadData();
  }

  private async loadData() {
    this.loading.set(true);
    try {
      // Load categories
      const categories = await this.appraisalService.getGoalCategories();
      this.allCategories.set(categories);

      // Load template data if editing
      if (this.isEdit() && this.templateId) {
        // Note: This would need to be implemented in AppraisalService
        // For now, we'll handle it gracefully
        try {
          const template = await this.getTemplate(this.templateId);
          this.populateForm(template);
        } catch (error) {
          this.snackBar.open('Failed to load template data', 'Close', { duration: 3000 });
        }
      }
    } catch (error) {
      this.snackBar.open('Failed to load data', 'Close', { duration: 3000 });
    } finally {
      this.loading.set(false);
    }
  }

  private async getTemplate(id: number): Promise<ExtendedGoalTemplate> {
    // This would need to be implemented in AppraisalService
    // For now, return a mock template
    return {
      temp_id: id,
      temp_title: 'Sample Template',
      temp_description: 'Sample description',
      temp_performance_factor: 'Quality',
      temp_importance: 'High',
      temp_weightage: 25,
      categories: []
    };
  }

  private populateForm(template: ExtendedGoalTemplate) {
    this.templateForm.patchValue({
      title: template.temp_title,
      description: template.temp_description,
      performanceFactor: template.temp_performance_factor,
      importance: template.temp_importance,
      weightage: template.temp_weightage
    });

    if (template.categories) {
      this.selectedCategories.set(template.categories.map(c => c.name));
    }
  }

  private isManagerOrAbove(): boolean {
    const user = this.authService.getCurrentUser();
    if (!user) return false;
    
    if (user.emp_roles && /manager|lead|head|director|vp|chief|cxo|cto|ceo|admin/i.test(user.emp_roles)) {
      return true;
    }
    
    if (typeof user.emp_roles_level === 'number') {
      return user.emp_roles_level > 2;
    }
    
    return false;
  }

  addCategory() {
    const name = this.newCategory.trim();
    if (!name) return;
    
    const current = this.selectedCategories();
    if (current.includes(name)) {
      this.newCategory = '';
      return;
    }
    
    this.selectedCategories.set([...current, name]);
    this.newCategory = '';
  }

  removeCategory(name: string) {
    const current = this.selectedCategories();
    this.selectedCategories.set(current.filter(c => c !== name));
  }

  async save() {
    if (this.templateForm.invalid) {
      this.templateForm.markAllAsTouched();
      return;
    }

    const formValue = this.templateForm.value;
    const payload = {
      temp_title: formValue.title.trim(),
      temp_description: formValue.description?.trim() || '',
      temp_performance_factor: formValue.performanceFactor?.trim() || '',
      temp_importance: formValue.importance?.trim() || '',
      temp_weightage: formValue.weightage,
      categories: this.selectedCategories()
    };

    this.saving.set(true);
    try {
      if (this.isEdit() && this.templateId) {
        // Update existing template
        await this.updateTemplate(this.templateId, payload);
        this.snackBar.open('Template updated successfully', 'Close', { duration: 3000 });
      } else {
        // Create new template
        await this.createTemplate(payload);
        this.snackBar.open('Template created successfully', 'Close', { duration: 3000 });
      }
      
      this.router.navigate(['/goal-templates']);
    } catch (error) {
      this.snackBar.open((error as any).message || 'Save failed', 'Close', { duration: 3000 });
    } finally {
      this.saving.set(false);
    }
  }

  private async createTemplate(payload: any): Promise<void> {
    // This would need to be implemented in AppraisalService
    // For now, simulate API call
    await new Promise(resolve => setTimeout(resolve, 1000));
  }

  private async updateTemplate(id: number, payload: any): Promise<void> {
    // This would need to be implemented in AppraisalService
    // For now, simulate API call
    await new Promise(resolve => setTimeout(resolve, 1000));
  }

  goBack() {
    this.router.navigate(['/goal-templates']);
  }

  goHome() {
    this.router.navigate(['/']);
  }
}
