// frontend/src/pages/appraisal-view/AppraisalView.tsx
import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { apiFetch } from "../../utils/api";
import { Card, CardContent, CardHeader } from "../../components/ui/card";
import { Slider } from "../../components/ui/slider";
import { Textarea } from "../../components/ui/textarea";
import { Button } from "../../components/ui/button";
import { Badge } from "../../components/ui/badge";
import { Progress } from "../../components/ui/progress";
import { useAuth } from "../../contexts/AuthContext";
import {
  Calendar,
  Target,
  Weight,
  MessageSquare,
  Star,
  ChevronLeft,
  ChevronRight,
  BarChart3,
  User,
  UserCheck,
  Eye,
  Home,
} from "lucide-react";

interface GoalCategory {
  id: number;
  name: string;
}
interface Goal {
  goal_id: number;
  goal_title: string;
  goal_description?: string | null;
  goal_importance?: string | null;
  goal_weightage: number;
  category?: GoalCategory | null;
}
interface AppraisalGoal {
  id: number;
  goal_id: number;
  goal: Goal;
  self_rating?: number | null;
  self_comment?: string | null;
  appraiser_rating?: number | null;
  appraiser_comment?: string | null;
}
interface AppraisalWithGoals {
  appraisal_id: number;
  appraisee_id: number;
  appraiser_id: number;
  reviewer_id: number;
  appraisal_type_id: number;
  appraisal_type_range_id?: number | null;
  start_date: string;
  end_date: string;
  status: string;
  appraisal_goals: AppraisalGoal[];
  appraiser_overall_comments?: string | null;
  appraiser_overall_rating?: number | null;
  reviewer_overall_comments?: string | null;
  reviewer_overall_rating?: number | null;
}

// Map API status to user-friendly text
const displayStatus = (s: string) =>
  s === "Submitted" ? "Waiting Acknowledgement" : s;

// Status badge coloring (neutral theme-aware styling)
const statusClass = (_s: string) => "bg-muted text-foreground border-border";

const AppraisalView = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [loading, setLoading] = useState(false);
  const [appraisal, setAppraisal] = useState<AppraisalWithGoals | null>(null);
  const [idx, setIdx] = useState(0); // 0..goals.length, where last index is overall page

  useEffect(() => {
    const load = async () => {
      if (!id) return;
      setLoading(true);
      const res = await apiFetch<AppraisalWithGoals>(
        `/api/appraisals/${encodeURIComponent(id)}`
      );
      if (res.ok && res.data) {
        setAppraisal(res.data);
      }
      setLoading(false);
    };
    load();
  }, [id]);

  // Role/Status-based access guard
  useEffect(() => {
    if (!appraisal) return;
    const empId = user?.emp_id;
    if (!empId) {
      navigate("/", { replace: true });
      return;
    }
    const status = appraisal.status;
    const isAppraisee = empId === appraisal.appraisee_id;
    const isAppraiser = empId === appraisal.appraiser_id;
    const isReviewer = empId === appraisal.reviewer_id;

    let allowed = false;
    if (isAppraisee) {
      // Appraisee can view only during Submitted (Waiting Acknowledgement), Self Assessment, or Complete
      allowed =
        status === "Submitted" ||
        status === "Appraisee Self Assessment" ||
        status === "Complete";
    } else if (isAppraiser) {
      // Appraiser should NOT view during Appraiser/Reviewer Evaluation; allow Complete only
      allowed = status === "Complete";
    } else if (isReviewer) {
      // Reviewer: allow Complete only (evaluation happens in its own page)
      allowed = status === "Complete";
    }

    if (!allowed) navigate("/", { replace: true });
  }, [appraisal, user?.emp_id, navigate]);

  const goals = appraisal?.appraisal_goals || [];
  const showOverall = appraisal?.status === "Complete";
  const totalGoals = goals.length;
  const maxIndex = showOverall ? totalGoals : Math.max(0, totalGoals - 1);
  const isOverallPage = showOverall && idx === totalGoals;
  const current = goals[idx];
  // Keep progress behavior consistent with prior implementation: 100% on overall page
  const progressPct =
    totalGoals > 0
      ? Math.round((Math.min(idx, totalGoals) / totalGoals) * 100)
      : 100;

  if (!appraisal)
    return (
      <div
        className="min-h-screen bg-background p-4 md:p-6 lg:p-8"
        aria-busy={loading}
      >
        <div className="mx-auto max-w-5xl">
          <div className="animate-pulse space-y-6">
            <div className="h-8 bg-muted rounded-lg w-1/3"></div>
            <div className="h-32 bg-muted rounded-xl"></div>
            <div className="h-96 bg-muted rounded-xl"></div>
          </div>
        </div>
      </div>
    );

  return (
    <div
      className="min-h-screen bg-background p-4 md:p-6 lg:p-8 animate-fade-in"
      aria-busy={loading}
    >
      <div className="mx-auto max-w-5xl space-y-6">
        {/* Header Card */}
        <Card className="shadow-medium border-0 glass-effect">
          <CardHeader className="pb-4">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <Eye className="h-5 w-5 text-primary" />
                </div>
                <div className="space-y-1">
                  <h1 className="text-2xl lg:text-3xl font-bold text-foreground">
                    Appraisal View
                  </h1>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Calendar className="h-4 w-4 text-muted-foreground" />
                    {new Date(appraisal.start_date).toLocaleDateString()} –{" "}
                    {new Date(appraisal.end_date).toLocaleDateString()}
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <Badge
                  variant="outline"
                  className={`px-3 py-1 text-sm font-medium ${statusClass(
                    appraisal.status
                  )}`}
                >
                  {displayStatus(appraisal.status)}
                </Badge>
                <div className="text-right">
                  <div className="text-sm font-medium text-foreground">
                    {isOverallPage
                      ? "Overall Summary"
                      : `Goal ${Math.min(
                          idx + 1,
                          totalGoals
                        )} of ${totalGoals}`}
                  </div>
                  <div className="text-xs text-muted-foreground">
                    {progressPct}% Complete
                  </div>
                </div>
              </div>
            </div>
            <Progress value={progressPct} className="h-2 mt-4" />
          </CardHeader>
        </Card>

        {!isOverallPage && current && (
          <Card className="shadow-medium border-0 glass-effect animate-slide-up">
            <CardHeader className="pb-4">
              <div className="flex items-start gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <Target className="h-5 w-5 text-primary" />
                </div>
                <div className="flex-1 space-y-2">
                  <h2 className="text-xl font-semibold text-foreground leading-tight">
                    {current.goal.goal_title}
                  </h2>
                  {current.goal.goal_description && (
                    <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
                      {current.goal.goal_description}
                    </p>
                  )}
                  <div className="flex flex-wrap items-center gap-3 text-xs">
                    <div className="flex items-center gap-1 text-muted-foreground">
                      <Weight className="h-3 w-3" />
                      <span>Weightage: {current.goal.goal_weightage}%</span>
                    </div>
                    {current.goal.category && (
                      <Badge variant="secondary" className="text-xs">
                        {current.goal.category.name}
                      </Badge>
                    )}
                  </div>
                </div>
              </div>
            </CardHeader>

            <CardContent className="space-y-6">
              {/* Self Assessment (read-only) */}
              <div className="rounded-lg border border-border bg-muted/40 p-4 space-y-3">
                <div className="flex items-center gap-2">
                  <User className="h-4 w-4 text-primary" />
                  <h3 className="text-sm font-medium text-foreground">
                    Employee Self Assessment
                  </h3>
                </div>
                <div className="space-y-3">
                  <div className="flex items-center gap-2">
                    <Star className="h-4 w-4 text-primary" />
                    <label className="text-sm font-medium text-foreground">
                      Self Rating
                    </label>
                    {current.self_rating && (
                      <Badge variant="outline" className="ml-auto">
                        {current.self_rating}/5
                      </Badge>
                    )}
                  </div>
                  <Slider
                    min={1}
                    max={5}
                    step={1}
                    value={
                      current.self_rating != null
                        ? [current.self_rating]
                        : undefined
                    }
                    disabled
                    className="opacity-70"
                  />
                  <div>
                    <label className="text-sm font-medium text-foreground flex items-center gap-2">
                      <MessageSquare className="h-4 w-4 text-primary" /> Self
                      Comments
                    </label>
                    <Textarea
                      rows={3}
                      value={current.self_comment ?? "No comments provided"}
                      disabled
                      className="bg-card/50 border-border resize-none"
                    />
                  </div>
                </div>
              </div>

              {/* Appraiser Evaluation (read-only, visible only when Complete) */}
              {showOverall && (
                <div className="rounded-lg border border-border bg-muted/40 p-4 space-y-3">
                  <div className="flex items-center gap-2">
                    <UserCheck className="h-4 w-4 text-primary" />
                    <h3 className="text-sm font-medium text-foreground">
                      Appraiser Evaluation
                    </h3>
                  </div>
                  <div className="space-y-3">
                    <div className="flex items-center gap-2">
                      <Star className="h-4 w-4 text-primary" />
                      <label className="text-sm font-medium text-foreground">
                        Appraiser Rating
                      </label>
                      {current.appraiser_rating && (
                        <Badge variant="outline" className="ml-auto">
                          {current.appraiser_rating}/5
                        </Badge>
                      )}
                    </div>
                    <Slider
                      min={1}
                      max={5}
                      step={1}
                      value={
                        current.appraiser_rating != null
                          ? [current.appraiser_rating]
                          : undefined
                      }
                      disabled
                      className="opacity-70"
                    />
                    <div>
                      <label className="text-sm font-medium text-foreground flex items-center gap-2">
                        <MessageSquare className="h-4 w-4 text-primary" />{" "}
                        Appraiser Comments
                      </label>
                      <Textarea
                        rows={4}
                        value={
                          current.appraiser_comment ?? "No comments provided"
                        }
                        disabled
                        className="bg-card/50 border-border resize-none"
                      />
                    </div>
                  </div>
                </div>
              )}

              {/* Navigation */}
              <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-border/50">
                <Button
                  variant="outline"
                  onClick={() => setIdx((i) => Math.max(0, i - 1))}
                  disabled={loading || idx === 0}
                  className="w-full sm:w-auto"
                >
                  <ChevronLeft className="h-4 w-4 mr-2" />
                  Previous Goal
                </Button>

                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <div
                    className="flex gap-1"
                    role="list"
                    aria-label="Progress steps"
                  >
                    {Array.from(
                      { length: showOverall ? totalGoals + 1 : totalGoals },
                      (_, i) => (
                        <div
                          key={i}
                          role="listitem"
                          aria-label={`Step ${i + 1} of ${
                            showOverall ? totalGoals + 1 : totalGoals
                          }${i === idx ? ", current step" : ""}`}
                          aria-current={i === idx ? "step" : undefined}
                          className={`w-2 h-2 rounded-full ${
                            i === idx
                              ? "bg-primary"
                              : i < idx
                              ? "bg-primary/60"
                              : "bg-border"
                          }`}
                        />
                      )
                    )}
                  </div>
                </div>

                <Button
                  onClick={() => setIdx((i) => Math.min(maxIndex, i + 1))}
                  disabled={loading || idx === maxIndex}
                  className="w-full sm:w-auto bg-primary hover:bg-primary/90 text-primary-foreground"
                >
                  {showOverall && idx === totalGoals - 1
                    ? "Overall Summary"
                    : "Next Goal"}
                  <ChevronRight className="h-4 w-4 ml-2" />
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {isOverallPage && (
          <Card className="shadow-medium border-0 glass-effect animate-slide-up">
            <CardHeader className="pb-4">
              <div className="flex items-start gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <BarChart3 className="h-5 w-5 text-primary" />
                </div>
                <div className="flex-1 space-y-1">
                  <h2 className="text-xl font-semibold text-foreground leading-tight">
                    Overall Evaluation
                  </h2>
                  <p className="text-sm text-muted-foreground">
                    Summary of appraiser and reviewer assessments
                  </p>
                </div>
              </div>
            </CardHeader>

            <CardContent className="space-y-6">
              <div className="grid gap-6 sm:grid-cols-2">
                {/* Appraiser Overall - read only */}
                <div className="rounded-lg border border-border bg-muted/40 p-4 space-y-3">
                  <div className="flex items-center gap-2">
                    <UserCheck className="h-4 w-4 text-primary" />
                    <h3 className="text-sm font-medium text-foreground">
                      Appraiser Overall Assessment
                    </h3>
                  </div>
                  <div className="space-y-3">
                    <div className="flex items-center gap-2">
                      <Star className="h-4 w-4 text-primary" />
                      <label className="text-sm font-medium text-foreground">
                        Overall Rating
                      </label>
                      {appraisal.appraiser_overall_rating && (
                        <Badge variant="outline" className="ml-auto">
                          {appraisal.appraiser_overall_rating}/5
                        </Badge>
                      )}
                    </div>
                    <Slider
                      min={1}
                      max={5}
                      step={1}
                      value={
                        appraisal.appraiser_overall_rating != null
                          ? [appraisal.appraiser_overall_rating]
                          : undefined
                      }
                      disabled
                      className="opacity-70"
                    />
                    <div>
                      <label className="text-sm font-medium text-foreground flex items-center gap-2">
                        <MessageSquare className="h-4 w-4 text-primary" />{" "}
                        Overall Comments
                      </label>
                      <Textarea
                        rows={4}
                        value={
                          appraisal.appraiser_overall_comments ??
                          "No comments provided"
                        }
                        disabled
                        className="bg-card/50 border-border resize-none"
                      />
                    </div>
                  </div>
                </div>

                {/* Reviewer Overall - read only */}
                <div className="rounded-lg border border-border bg-muted/40 p-4 space-y-3">
                  <div className="flex items-center gap-2">
                    <Eye className="h-4 w-4 text-primary" />
                    <h3 className="text-sm font-medium text-foreground">
                      Reviewer Overall Assessment
                    </h3>
                  </div>
                  <div className="space-y-3">
                    <div className="flex items-center gap-2">
                      <Star className="h-4 w-4 text-primary" />
                      <label className="text-sm font-medium text-foreground">
                        Overall Rating
                      </label>
                      {appraisal.reviewer_overall_rating && (
                        <Badge variant="outline" className="ml-auto">
                          {appraisal.reviewer_overall_rating}/5
                        </Badge>
                      )}
                    </div>
                    <Slider
                      min={1}
                      max={5}
                      step={1}
                      value={
                        appraisal.reviewer_overall_rating != null
                          ? [appraisal.reviewer_overall_rating]
                          : undefined
                      }
                      disabled
                      className="opacity-70"
                    />
                    <div>
                      <label className="text-sm font-medium text-foreground flex items-center gap-2">
                        <MessageSquare className="h-4 w-4 text-primary" />{" "}
                        Overall Comments
                      </label>
                      <Textarea
                        rows={5}
                        value={
                          appraisal.reviewer_overall_comments ??
                          "No comments provided"
                        }
                        disabled
                        className="bg-card/50 border-border resize-none"
                      />
                    </div>
                  </div>
                </div>
              </div>

              {/* Navigation */}
              <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-border/50">
                <Button
                  variant="outline"
                  onClick={() => setIdx((i) => Math.max(0, i - 1))}
                  disabled={loading}
                  className="w-full sm:w-auto"
                >
                  <ChevronLeft className="h-4 w-4 mr-2" />
                  Previous Goal
                </Button>
                <Button
                  onClick={() => navigate("/")}
                  className="w-full sm:w-auto bg-primary hover:bg-primary/90 text-primary-foreground flex items-center gap-2"
                  aria-label="Home"
                  title="Home"
                >
                  <Home className="h-4 w-4" />
                  <span className="hidden sm:inline">Go Home</span>
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
};

export default AppraisalView;

// frontend-angular/src/app/features/appraisal/appraisal-view/appraisal-view.component.ts
import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatSliderModule } from '@angular/material/slider';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatIconModule } from '@angular/material/icon';
import { MatSnackBar } from '@angular/material/snack-bar';
import { AppraisalService, AppraisalWithGoals, AppraisalGoal, Goal, GoalCategory } from '@core/services/appraisal.service';
import { AuthService } from '@core/services/auth.service';

@Component({
  selector: 'app-appraisal-view',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatProgressBarModule,
    MatSliderModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule
  ],
  template: `
    <div class="min-h-screen bg-background p-4 md:p-6 lg:p-8">
      <div class="mx-auto max-w-5xl space-y-6">
        
        @if (loading()) {
          <div class="animate-pulse space-y-6">
            <div class="h-8 bg-muted rounded-lg w-1/3"></div>
            <div class="h-32 bg-muted rounded-xl"></div>
            <div class="h-96 bg-muted rounded-xl"></div>
          </div>
        } @else if (appraisal()) {
          <!-- Header Card -->
          <mat-card class="shadow-medium border-0">
            <mat-card-header class="pb-4">
              <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 w-full">
                <div class="flex items-center gap-3">
                  <div class="p-2 rounded-lg bg-primary/10">
                    <mat-icon class="h-5 w-5 text-primary">visibility</mat-icon>
                  </div>
                  <div class="space-y-1">
                    <h1 class="text-2xl lg:text-3xl font-bold text-foreground">Appraisal View</h1>
                    <div class="flex items-center gap-2 text-sm text-muted-foreground">
                      <mat-icon class="h-4 w-4">calendar_today</mat-icon>
                      {{ formatDate(appraisal()!.start_date) }} – {{ formatDate(appraisal()!.end_date) }}
                    </div>
                  </div>
                </div>
                <div class="flex items-center gap-3">
                  <span class="px-3 py-1 text-sm font-medium bg-muted text-foreground border border-border rounded-md">
                    {{ displayStatus(appraisal()!.status) }}
                  </span>
                  <div class="text-right">
                    <div class="text-sm font-medium text-foreground">
                      {{ isOverallPage() ? 'Overall Summary' : 'Goal ' + Math.min(currentIndex() + 1, totalGoals()) + ' of ' + totalGoals() }}
                    </div>
                    <div class="text-xs text-muted-foreground">{{ progressPercentage() }}% Complete</div>
                  </div>
                </div>
              </div>
              <mat-progress-bar 
                [value]="progressPercentage()" 
                class="h-2 mt-4">
              </mat-progress-bar>
            </mat-card-header>
          </mat-card>

          <!-- Goal View Card -->
          @if (!isOverallPage() && currentGoal()) {
            <mat-card class="shadow-medium border-0">
              <mat-card-header class="pb-4">
                <div class="flex items-start gap-3 w-full">
                  <div class="p-2 rounded-lg bg-primary/10">
                    <mat-icon class="h-5 w-5 text-primary">track_changes</mat-icon>
                  </div>
                  <div class="flex-1 space-y-2">
                    <h2 class="text-xl font-semibold text-foreground leading-tight">{{ currentGoal()!.goal.goal_title }}</h2>
                    @if (currentGoal()!.goal.goal_description) {
                      <p class="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">{{ currentGoal()!.goal.goal_description }}</p>
                    }
                    <div class="flex flex-wrap items-center gap-3 text-xs">
                      <div class="flex items-center gap-1 text-muted-foreground">
                        <mat-icon class="h-3 w-3">fitness_center</mat-icon>
                        <span>Weightage: {{ currentGoal()!.goal.goal_weightage }}%</span>
                      </div>
                      @if (currentGoal()!.goal.category) {
                        <span class="text-xs bg-secondary text-secondary-foreground px-2 py-1 rounded">
                          {{ currentGoal()!.goal.category!.name }}
                        </span>
                      }
                    </div>
                  </div>
                </div>
              </mat-card-header>

              <mat-card-content class="space-y-6">
                <!-- Self Assessment (read-only) -->
                <div class="rounded-lg border border-border bg-muted/40 p-4 space-y-3">
                  <div class="flex items-center gap-2">
                    <mat-icon class="h-4 w-4 text-primary">person</mat-icon>
                    <h3 class="text-sm font-medium text-foreground">Employee Self Assessment</h3>
                  </div>
                  <div class="space-y-3">
                    <div class="flex items-center gap-2">
                      <mat-icon class="h-4 w-4 text-primary">star</mat-icon>
                      <label class="text-sm font-medium text-foreground">Self Rating</label>
                      @if (currentGoal()!.self_rating) {
                        <span class="ml-auto px-2 py-1 text-xs border rounded">{{ currentGoal()!.self_rating }}/5</span>
                      }
                    </div>
                    <mat-slider 
                      min="1" 
                      max="5" 
                      step="1" 
                      discrete
                      disabled
                      class="opacity-70">
                      <input matSliderThumb [value]="currentGoal()!.self_rating || 1">
                    </mat-slider>
                    <div>
                      <label class="text-sm font-medium text-foreground flex items-center gap-2">
                        <mat-icon class="h-4 w-4 text-primary">chat_bubble_outline</mat-icon> 
                        Self Comments
                      </label>
                      <mat-form-field appearance="outline" class="w-full">
                        <textarea 
                          matInput 
                          rows="3"
                          [value]="currentGoal()!.self_comment || 'No comments provided'"
                          readonly
                          class="bg-card/50 border-border resize-none">
                        </textarea>
                      </mat-form-field>
                    </div>
                  </div>
                </div>

                <!-- Appraiser Evaluation (read-only, visible only when Complete) -->
                @if (showOverall()) {
                  <div class="rounded-lg border border-border bg-muted/40 p-4 space-y-3">
                    <div class="flex items-center gap-2">
                      <mat-icon class="h-4 w-4 text-primary">verified_user</mat-icon>
                      <h3 class="text-sm font-medium text-foreground">Appraiser Evaluation</h3>
                    </div>
                    <div class="space-y-3">
                      <div class="flex items-center gap-2">
                        <mat-icon class="h-4 w-4 text-primary">star</mat-icon>
                        <label class="text-sm font-medium text-foreground">Appraiser Rating</label>
                        @if (currentGoal()!.appraiser_rating) {
                          <span class="ml-auto px-2 py-1 text-xs border rounded">{{ currentGoal()!.appraiser_rating }}/5</span>
                        }
                      </div>
                      <mat-slider 
                        min="1" 
                        max="5" 
                        step="1" 
                        discrete
                        disabled
                        class="opacity-70">
                        <input matSliderThumb [value]="currentGoal()!.appraiser_rating || 1">
                      </mat-slider>
                      <div>
                        <label class="text-sm font-medium text-foreground flex items-center gap-2">
                          <mat-icon class="h-4 w-4 text-primary">chat_bubble_outline</mat-icon> 
                          Appraiser Comments
                        </label>
                        <mat-form-field appearance="outline" class="w-full">
                          <textarea 
                            matInput 
                            rows="4"
                            [value]="currentGoal()!.appraiser_comment || 'No comments provided'"
                            readonly
                            class="bg-card/50 border-border resize-none">
                          </textarea>
                        </mat-form-field>
                      </div>
                    </div>
                  </div>
                }

                <!-- Navigation -->
                <div class="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-border/50">
                  <button 
                    mat-stroked-button
                    (click)="previousGoal()" 
                    [disabled]="loading() || currentIndex() === 0"
                    class="w-full sm:w-auto">
                    <mat-icon>chevron_left</mat-icon>
                    Previous Goal
                  </button>

                  <div class="flex items-center gap-2 text-xs text-muted-foreground">
                    <div class="flex gap-1">
                      @for (goal of goals(); track goal.id; let i = $index) {
                        <div
                          class="w-2 h-2 rounded-full"
                          [class]="i === currentIndex() ? 'bg-primary' : i < currentIndex() ? 'bg-primary/60' : 'bg-border'">
                        </div>
                      }
                      @if (showOverall()) {
                        <div
                          class="w-2 h-2 rounded-full"
                          [class]="isOverallPage() ? 'bg-primary' : currentIndex() >= totalGoals() ? 'bg-primary/60' : 'bg-border'">
                        </div>
                      }
                    </div>
                  </div>

                  <button
                    mat-raised-button
                    color="primary"
                    (click)="nextGoal()"
                    [disabled]="loading() || currentIndex() === maxIndex()"
                    class="w-full sm:w-auto">
                    {{ showOverall() && currentIndex() === totalGoals() - 1 ? 'Overall Summary' : 'Next Goal' }}
                    <mat-icon>chevron_right</mat-icon>
                  </button>
                </div>
              </mat-card-content>
            </mat-card>
          }

          <!-- Overall Summary Card -->
          @if (isOverallPage()) {
            <mat-card class="shadow-medium border-0">
              <mat-card-header class="pb-4">
                <div class="flex items-start gap-3 w-full">
                  <div class="p-2 rounded-lg bg-primary/10">
                    <mat-icon class="h-5 w-5 text-primary">bar_chart</mat-icon>
                  </div>
                  <div class="flex-1 space-y-1">
                    <h2 class="text-xl font-semibold text-foreground leading-tight">Overall Evaluation</h2>
                    <p class="text-sm text-muted-foreground">Summary of appraiser and reviewer assessments</p>
                  </div>
                </div>
              </mat-card-header>

              <mat-card-content class="space-y-6">
                <div class="grid gap-6 sm:grid-cols-2">
                  <!-- Appraiser Overall - read only -->
                  <div class="rounded-lg border border-border bg-muted/40 p-4 space-y-3">
                    <div class="flex items-center gap-2">
                      <mat-icon class="h-4 w-4 text-primary">verified_user</mat-icon>
                      <h3 class="text-sm font-medium text-foreground">Appraiser Overall Assessment</h3>
                    </div>
                    <div class="space-y-3">
                      <div class="flex items-center gap-2">
                        <mat-icon class="h-4 w-4 text-primary">star</mat-icon>
                        <label class="text-sm font-medium text-foreground">Overall Rating</label>
                        @if (appraisal()!.appraiser_overall_rating) {
                          <span class="ml-auto px-2 py-1 text-xs border rounded">{{ appraisal()!.appraiser_overall_rating }}/5</span>
                        }
                      </div>
                      <mat-slider 
                        min="1" 
                        max="5" 
                        step="1" 
                        discrete
                          disabled
                        class="opacity-70">
                        <input matSliderThumb [value]="appraisal()!.appraiser_overall_rating || 1">
                      </mat-slider>
                      <div>
                        <label class="text-sm font-medium text-foreground flex items-center gap-2">
                          <mat-icon class="h-4 w-4 text-primary">chat_bubble_outline</mat-icon> 
                          Overall Comments
                        </label>
                        <mat-form-field appearance="outline" class="w-full">
                          <textarea 
                            matInput 
                            rows="4"
                            [value]="appraisal()!.appraiser_overall_comments || 'No comments provided'"
                            readonly
                            class="bg-card/50 border-border resize-none">
                          </textarea>
                        </mat-form-field>
                      </div>
                    </div>
                  </div>

                  <!-- Reviewer Overall - read only -->
                  <div class="rounded-lg border border-border bg-muted/40 p-4 space-y-3">
                    <div class="flex items-center gap-2">
                      <mat-icon class="h-4 w-4 text-primary">visibility</mat-icon>
                      <h3 class="text-sm font-medium text-foreground">Reviewer Overall Assessment</h3>
                    </div>
                    <div class="space-y-3">
                      <div class="flex items-center gap-2">
                        <mat-icon class="h-4 w-4 text-primary">star</mat-icon>
                        <label class="text-sm font-medium text-foreground">Overall Rating</label>
                        @if (appraisal()!.reviewer_overall_rating) {
                          <span class="ml-auto px-2 py-1 text-xs border rounded">{{ appraisal()!.reviewer_overall_rating }}/5</span>
                        }
                      </div>
                      <mat-slider 
                        min="1" 
                        max="5" 
                        step="1" 
                        discrete
                        disabled
                        class="opacity-70">
                        <input matSliderThumb [value]="appraisal()!.reviewer_overall_rating || 1">
                      </mat-slider>
                      <div>
                        <label class="text-sm font-medium text-foreground flex items-center gap-2">
                          <mat-icon class="h-4 w-4 text-primary">chat_bubble_outline</mat-icon> 
                          Overall Comments
                        </label>
                        <mat-form-field appearance="outline" class="w-full">
                          <textarea 
                            matInput 
                            rows="5"
                            [value]="appraisal()!.reviewer_overall_comments || 'No comments provided'"
                            readonly
                            class="bg-card/50 border-border resize-none">
                          </textarea>
                        </mat-form-field>
                      </div>
                    </div>
                  </div>
                </div>

                <!-- Navigation -->
                <div class="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-border/50">
                  <button 
                    mat-stroked-button
                    (click)="previousGoal()" 
                    [disabled]="loading()"
                    class="w-full sm:w-auto">
                    <mat-icon>chevron_left</mat-icon>
                    Previous Goal
                  </button>
                  <button
                    mat-raised-button
                    color="primary"
                    (click)="goHome()"
                    class="w-full sm:w-auto">
                    <mat-icon>home</mat-icon>
                    <span class="hidden sm:inline">Go Home</span>
                  </button>
                </div>
              </mat-card-content>
            </mat-card>
          }
        }
      </div>
    </div>
  `,
  styles: [`
    .shadow-medium {
      box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
    }
    
    mat-card {
      border-radius: 12px;
    }
    
    mat-progress-bar {
      height: 8px;
      border-radius: 4px;
    }
    
    .animate-pulse {
      animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
    }
    
    @keyframes pulse {
      0%, 100% {
        opacity: 1;
      }
      50% {
        opacity: .5;
      }
    }
  `]
})
export class AppraisalViewComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private snackBar = inject(MatSnackBar);
  private appraisalService = inject(AppraisalService);
  private authService = inject(AuthService);

  Math = Math; // Make Math available in template

  loading = signal(false);
  appraisal = signal<AppraisalWithGoals | null>(null);
  currentIndex = signal(0);

  goals = computed(() => this.appraisal()?.appraisal_goals || []);
  totalGoals = computed(() => this.goals().length);
  showOverall = computed(() => this.appraisal()?.status === 'Complete');
  maxIndex = computed(() => this.showOverall() ? this.totalGoals() : Math.max(0, this.totalGoals() - 1));
  isOverallPage = computed(() => this.showOverall() && this.currentIndex() === this.totalGoals());
  currentGoal = computed(() => this.goals()[this.currentIndex()]);
  progressPercentage = computed(() => 
    this.totalGoals() > 0 ? Math.round((Math.min(this.currentIndex(), this.totalGoals()) / this.totalGoals()) * 100) : 100
  );

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.loadAppraisal(id);
    }
  }

  private async loadAppraisal(id: string) {
    this.loading.set(true);
    try {
      const appraisal: AppraisalWithGoals = await this.appraisalService.getAppraisal(parseInt(id));
      this.appraisal.set(appraisal);
      
      // Role/Status-based access guard
      const user = this.authService.getCurrentUser();
      if (!user) {
        this.router.navigate(['/'], { replaceUrl: true });
        return;
      }

      const status = appraisal.status;
      const isAppraisee = user.emp_id === appraisal.appraisee_id;
      const isAppraiser = user.emp_id === appraisal.appraiser_id;
      const isReviewer = user.emp_id === appraisal.reviewer_id;

      let allowed = false;
      if (isAppraisee) {
        // Appraisee can view only during Submitted (Waiting Acknowledgement), Self Assessment, or Complete
        allowed = status === 'Submitted' || status === 'Appraisee Self Assessment' || status === 'Complete';
      } else if (isAppraiser) {
        // Appraiser should NOT view during Appraiser/Reviewer Evaluation; allow Complete only
        allowed = status === 'Complete';
      } else if (isReviewer) {
        // Reviewer: allow Complete only (evaluation happens in its own page)
        allowed = status === 'Complete';
      }

      if (!allowed) {
        this.router.navigate(['/'], { replaceUrl: true });
      }
    } catch (error) {
      this.snackBar.open((error as any).message || 'Failed to load appraisal', 'Close', { duration: 3000 });
    } finally {
      this.loading.set(false);
    }
  }

  displayStatus(status: string): string {
    return status === 'Submitted' ? 'Waiting Acknowledgement' : status;
  }

  previousGoal() {
    if (this.currentIndex() > 0) {
      this.currentIndex.set(this.currentIndex() - 1);
    }
  }

  nextGoal() {
    if (this.currentIndex() < this.maxIndex()) {
      this.currentIndex.set(this.currentIndex() + 1);
    }
  }

  goHome() {
    this.router.navigate(['/']);
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleDateString();
  }
}
