// frontend-angular/src/app/features/appraisal/create-appraisal/edit-goal-modal/edit-goal-modal.component.ts
import { Component, Inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { MatDialogRef, MAT_DIALOG_DATA, MatDialogModule } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar } from '@angular/material/snack-bar';
import { environment } from '../../../../../environments/environment';

interface GoalCategory {
  id: number;
  name: string;
}

interface Goal {
  goal_id: number;
  goal_title: string;
  goal_description: string;
  goal_weightage: number;
  goal_importance: 'High' | 'Medium' | 'Low';
  category?: {
    id: number;
    name: string;
  };
}

interface GoalRecord {
  goal: Goal;
}

interface EditGoalData {
  goalData: GoalRecord;
  remainingWeightage: number;
}

interface UpdateGoalRequest {
  goal_title: string;
  goal_description: string;
  goal_weightage: number;
  goal_importance: 'High' | 'Medium' | 'Low';
  goal_category_id?: number;
}

@Component({
  selector: 'app-edit-goal-modal',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatDialogModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule
  ],
  template: `
    <div class="p-6">
      <h2 class="text-xl font-semibold mb-4">Edit Goal</h2>
      
      <form [formGroup]="goalForm" class="space-y-4">
        <!-- Goal Title -->
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Goal Title</mat-label>
          <input matInput formControlName="goal_title" placeholder="Enter goal title">
          <mat-error *ngIf="goalForm.get('goal_title')?.hasError('required')">
            Goal title is required
          </mat-error>
        </mat-form-field>

        <!-- Goal Description -->
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Goal Description</mat-label>
          <textarea matInput formControlName="goal_description" rows="3" placeholder="Enter goal description"></textarea>
        </mat-form-field>

        <!-- Goal Weightage -->
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Weightage (%)</mat-label>
          <input matInput type="number" formControlName="goal_weightage" 
                 [max]="maxWeightage" min="1" placeholder="Enter weightage">
          <mat-hint>Available: {{ data.remainingWeightage }}% (+ current {{ data.goalData.goal.goal_weightage }}%)</mat-hint>
          <mat-error *ngIf="goalForm.get('goal_weightage')?.hasError('required')">
            Weightage is required
          </mat-error>
          <mat-error *ngIf="goalForm.get('goal_weightage')?.hasError('min')">
            Weightage must be at least 1%
          </mat-error>
          <mat-error *ngIf="goalForm.get('goal_weightage')?.hasError('max')">
            Weightage cannot exceed {{ maxWeightage }}%
          </mat-error>
        </mat-form-field>

        <!-- Goal Importance -->
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Importance</mat-label>
          <mat-select formControlName="goal_importance">
            <mat-option value="High">High</mat-option>
            <mat-option value="Medium">Medium</mat-option>
            <mat-option value="Low">Low</mat-option>
          </mat-select>
          <mat-error *ngIf="goalForm.get('goal_importance')?.hasError('required')">
            Importance is required
          </mat-error>
        </mat-form-field>

        <!-- Goal Category -->
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Category (Optional)</mat-label>
          <mat-select formControlName="goal_category_id">
            <mat-option value="">No Category</mat-option>
            <mat-option *ngFor="let category of categories()" [value]="category.id">
              {{ category.name }}
            </mat-option>
          </mat-select>
        </mat-form-field>
      </form>

      <!-- Actions -->
      <div class="flex justify-end gap-3 mt-6">
        <button mat-button (click)="onCancel()">Cancel</button>
        <button mat-raised-button color="primary" 
                (click)="onSave()" 
                [disabled]="!goalForm.valid || loading()">
          {{ loading() ? 'Updating...' : 'Update Goal' }}
        </button>
      </div>
    </div>
  `
})
export class EditGoalModalComponent implements OnInit {
  goalForm: FormGroup;
  categories = signal<GoalCategory[]>([]);
  loading = signal(false);
  maxWeightage: number;

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private snackBar: MatSnackBar,
    private dialogRef: MatDialogRef<EditGoalModalComponent>,
    @Inject(MAT_DIALOG_DATA) public data: EditGoalData
  ) {
    this.maxWeightage = data.remainingWeightage + data.goalData.goal.goal_weightage;
    
    this.goalForm = this.fb.group({
      goal_title: [data.goalData.goal.goal_title, Validators.required],
      goal_description: [data.goalData.goal.goal_description],
      goal_weightage: [data.goalData.goal.goal_weightage, [Validators.required, Validators.min(1), Validators.max(this.maxWeightage)]],
      goal_importance: [data.goalData.goal.goal_importance, Validators.required],
      goal_category_id: [data.goalData.goal.category?.id || '']
    });
  }

  ngOnInit() {
    this.loadCategories();
  }

  private async loadCategories() {
    try {
      const categories = await this.http.get<GoalCategory[]>(`${environment.apiUrl}/api/goals/categories`).toPromise();
      this.categories.set(categories || []);
    } catch (error) {
      console.error('Error loading categories:', error);
    }
  }

  async onSave() {
    if (!this.goalForm.valid) {
      return;
    }

    try {
      this.loading.set(true);
      const formValue = this.goalForm.value;
      
      const request: UpdateGoalRequest = {
        goal_title: formValue.goal_title,
        goal_description: formValue.goal_description,
        goal_weightage: Number(formValue.goal_weightage),
        goal_importance: formValue.goal_importance,
        goal_category_id: formValue.goal_category_id || undefined
      };

      const response = await this.http.put<any>(
        `${environment.apiUrl}/api/goals/${this.data.goalData.goal.goal_id}`,
        request
      ).toPromise();

      this.snackBar.open('Goal updated successfully', 'Close', { duration: 3000 });
      this.dialogRef.close(response);
    } catch (error) {
      console.error('Error updating goal:', error);
      this.snackBar.open('Error updating goal', 'Close', { duration: 3000 });
    } finally {
      this.loading.set(false);
    }
  }

  onCancel() {
    this.dialogRef.close();
  }
}

// frontend/src/features/goals/EditGoalModal.tsx
import { useState, useEffect } from "react";
import { apiFetch } from "../../utils/api";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "../../components/ui/dialog";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Textarea } from "../../components/ui/textarea";
import { Label } from "../../components/ui/label";
import {
  Select as UiSelect,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "../../components/ui/select";
import { Edit3, Target, Weight, Save, X } from "lucide-react";
import { toast } from "sonner";

interface EditGoalModalProps {
  open: boolean;
  onClose: () => void;
  onGoalUpdated: (goal: AppraisalGoal) => void;
  goalData: AppraisalGoal | null;
  remainingWeightage?: number;
}

interface Category {
  id: number;
  name: string;
}

interface AppraisalGoal {
  id: number;
  appraisal_id: number;
  goal_id: number;
  goal: {
    goal_id: number;
    goal_title: string;
    goal_description: string;
    goal_performance_factor: string;
    goal_importance: string;
    goal_weightage: number;
    category_id: number;
    category: Category;
  };
}

interface GoalFormValues {
  goal_title: string;
  goal_description: string;
  goal_performance_factor: string;
  goal_importance: string;
  goal_weightage: number;
  category_id: number;
}

const EditGoalModal = ({
  open,
  onClose,
  onGoalUpdated,
  goalData,
  remainingWeightage = 100,
}: EditGoalModalProps) => {
  const [loading, setLoading] = useState(false);
  const [categories, setCategories] = useState<Category[]>([]);
  const [loadingCategories, setLoadingCategories] = useState(false);
  const [formValues, setFormValues] = useState<GoalFormValues>({
    goal_title: "",
    goal_description: "",
    goal_performance_factor: "",
    goal_importance: "",
    goal_weightage: 0,
    category_id: 0,
  });

  // Load categories when modal opens
  useEffect(() => {
    if (open) {
      loadCategories();
    }
  }, [open]);

  // Prefill form when goalData changes
  useEffect(() => {
    if (open && goalData) {
      setFormValues({
        goal_title: goalData.goal.goal_title,
        goal_description: goalData.goal.goal_description,
        goal_performance_factor: goalData.goal.goal_performance_factor,
        goal_importance: goalData.goal.goal_importance,
        goal_weightage: goalData.goal.goal_weightage,
        category_id: goalData.goal.category_id,
      });
    }
  }, [open, goalData]);

  const loadCategories = async () => {
    setLoadingCategories(true);
    try {
      const result = await apiFetch<Category[]>("/api/goals/categories");
      if (result.ok && result.data) {
        setCategories(result.data);
      }
    } catch (error) {
      console.error("Failed to load categories:", error);
    } finally {
      setLoadingCategories(false);
    }
  };

  const handleSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!goalData) {
      toast.error("No goal data available");
      return;
    }

    const values = formValues;

    // Basic validation
    if (
      !values.goal_title ||
      !values.goal_description ||
      !values.goal_performance_factor ||
      !values.goal_importance ||
      !values.category_id ||
      !values.goal_weightage
    ) {
      toast.error("Please complete all fields before submitting");
      return;
    }
    if (values.goal_weightage < 1 || values.goal_weightage > 100) {
      toast.error("Weightage must be between 1 and 100");
      return;
    }

    // remainingWeightage already includes the current goal's weight allowance
    const availableWeightage = remainingWeightage;
    if (values.goal_weightage > availableWeightage) {
      toast.error(`Must be <= available ${availableWeightage}%`);
      return;
    }

    setLoading(true);
    try {
      const updatedGoal: AppraisalGoal = {
        ...goalData,
        goal: {
          ...goalData.goal,
          goal_title: values.goal_title,
          goal_description: values.goal_description,
          goal_performance_factor: values.goal_performance_factor,
          goal_importance: values.goal_importance,
          goal_weightage: values.goal_weightage,
          category_id: values.category_id,
          category:
            categories.find((c) => c.id === values.category_id) ||
            goalData.goal.category,
        },
      };

      toast.success("Goal updated", {
        description: "Will be saved on submit.",
      });
      onGoalUpdated(updatedGoal);
      handleCancel();
    } catch (error: any) {
      toast.error(error.message || "Failed to update goal");
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = () => {
    setFormValues({
      goal_title: "",
      goal_description: "",
      goal_performance_factor: "",
      goal_importance: "",
      goal_weightage: 0,
      category_id: 0,
    });
    onClose();
  };

  const maxWeightage = remainingWeightage;

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        if (!o) handleCancel();
      }}
    >
      <DialogContent className="max-w-[95vw] sm:max-w-4xl max-h-[85vh] sm:max-h-[90vh] overflow-auto nice-scrollbar p-4 sm:p-6">
        <DialogHeader className="pb-3">
          <div className="flex items-center justify-between gap-3">
            <div className="p-2 rounded-lg bg-primary/10">
              <Edit3 className="h-5 w-5 text-primary" />
            </div>
            <div>
              <DialogTitle className="text-lg sm:text-xl font-semibold text-foreground">
                Edit Goal
              </DialogTitle>
              <p className="text-sm text-muted-foreground mt-1">
                Update the performance goal details
              </p>
            </div>
            <div className="text-xs text-muted-foreground ml-auto">
              Remaining: <span className="font-medium">{maxWeightage}%</span>
            </div>
          </div>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="rounded-md border p-4 space-y-4">
            <div className="grid gap-4">
              <div className="space-y-2">
                <Label
                  htmlFor="goal_title"
                  className="text-sm font-medium text-foreground flex items-center gap-2"
                >
                  <Target className="h-4 w-4 text-primary" />
                  Goal Title
                </Label>
                <Input
                  id="goal_title"
                  placeholder="Enter a clear, specific goal title"
                  value={formValues.goal_title}
                  onChange={(e) =>
                    setFormValues((v) => ({ ...v, goal_title: e.target.value }))
                  }
                  className="h-11 focus:ring-2 focus:ring-primary/20 border-border/50"
                  required
                />
              </div>

              <div className="space-y-2">
                <Label
                  htmlFor="goal_description"
                  className="text-sm font-medium text-foreground"
                >
                  Goal Description
                </Label>
                <Textarea
                  id="goal_description"
                  rows={4}
                  placeholder="Provide a detailed description of what needs to be achieved..."
                  value={formValues.goal_description}
                  onChange={(e) =>
                    setFormValues((v) => ({
                      ...v,
                      goal_description: e.target.value,
                    }))
                  }
                  className="resize-none focus:ring-2 focus:ring-primary/20 border-border/50"
                />
              </div>

              <div className="space-y-2">
                <Label
                  htmlFor="goal_performance_factor"
                  className="text-sm font-medium text-foreground"
                >
                  Performance Factors
                </Label>
                <Textarea
                  id="goal_performance_factor"
                  rows={3}
                  placeholder="Describe how performance will be measured and evaluated..."
                  value={formValues.goal_performance_factor}
                  onChange={(e) =>
                    setFormValues((v) => ({
                      ...v,
                      goal_performance_factor: e.target.value,
                    }))
                  }
                  className="resize-none focus:ring-2 focus:ring-primary/20 border-border/50"
                  required
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label
                    htmlFor="goal_importance"
                    className="text-sm font-medium text-foreground"
                  >
                    Importance Level
                  </Label>
                  <UiSelect
                    value={formValues.goal_importance}
                    onValueChange={(value) =>
                      setFormValues((v) => ({ ...v, goal_importance: value }))
                    }
                  >
                    <SelectTrigger className="h-11 focus:ring-2 focus:ring-primary/20 border-border/50">
                      <SelectValue placeholder="Select importance level" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="High">🔴 High Priority</SelectItem>
                      <SelectItem value="Medium">🟡 Medium Priority</SelectItem>
                      <SelectItem value="Low">🟢 Low Priority</SelectItem>
                    </SelectContent>
                  </UiSelect>
                </div>

                <div className="space-y-2">
                  <Label
                    htmlFor="category_id"
                    className="text-sm font-medium text-foreground"
                  >
                    Category
                  </Label>
                  <UiSelect
                    value={
                      formValues.category_id
                        ? String(formValues.category_id)
                        : ""
                    }
                    onValueChange={(value) =>
                      setFormValues((v) => ({
                        ...v,
                        category_id: Number.parseInt(value) || 0,
                      }))
                    }
                  >
                    <SelectTrigger className="h-11 focus:ring-2 focus:ring-primary/20 border-border/50">
                      <SelectValue
                        placeholder={
                          loadingCategories ? "Loading..." : "Select category"
                        }
                      />
                    </SelectTrigger>
                    <SelectContent>
                      {categories.map((cat) => (
                        <SelectItem key={cat.id} value={String(cat.id)}>
                          {cat.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </UiSelect>
                </div>
              </div>

              <div className="space-y-2">
                <Label
                  htmlFor="goal_weightage"
                  className="text-sm font-medium text-foreground flex items-center gap-2"
                >
                  <Weight className="h-4 w-4 text-amber-500" />
                  Weightage (%)
                </Label>
                <Input
                  id="goal_weightage"
                  type="number"
                  min="1"
                  max={maxWeightage}
                  placeholder="Enter weightage percentage"
                  value={formValues.goal_weightage || ""}
                  onChange={(e) =>
                    setFormValues((v) => ({
                      ...v,
                      goal_weightage: Number.parseInt(e.target.value) || 0,
                    }))
                  }
                  className="h-11 focus:ring-2 focus:ring-primary/20 border-border/50"
                  required
                />
                <div className="flex items-center justify-between text-xs">
                  <span className="text-muted-foreground">
                    Remaining weightage:{" "}
                    <span className="font-medium text-foreground">
                      {maxWeightage}%
                    </span>
                  </span>
                  {maxWeightage <= 0 && (
                    <span className="text-red-600 font-medium">
                      No weightage remaining
                    </span>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row justify-end gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={handleCancel}
              disabled={loading}
              className="w-full sm:w-auto"
              title="Cancel"
              aria-label="Cancel"
            >
              <X className="hidden sm:inline h-4 w-4 sm:mr-2" />
              <span className="sm:ml-2">Cancel</span>
            </Button>
            <Button
              type="submit"
              disabled={loading}
              className="w-full sm:w-auto"
              title="Update goal"
              aria-label="Update goal"
            >
              <Save className="hidden sm:inline h-4 w-4 sm:mr-2" />
              <span className="sm:ml-2">Update Goal</span>
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default EditGoalModal;
